layout_spectrum: 0.4567284937076603
typography_spectrum: 0.6873965840355153
color:
  lightness: 0.42077339972941075
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  saturation: 0.4259495047841332
  brandStrength: 0.3073241414848051
  rhythmicContrast: 0.1792941111156551
coverPrefs:
  filter: false
name: nathN
analytics: {}
purpose:
  - type: contact
    url: 'tel:16009195'
    label: Call 1three zero five 600 9195
  - type: contact
    url: 'mailto:contrerasnathan@yahoo.de'
    label: let's communicate
github: true
author:
  name: nathN
  email: contrerasnathan@yahoo.de
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b6be6cb-6e36-41d1-a448-de293f810657.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b6be6cb-6e36-41d1-a448-de293f810657.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content_rating:
  adult: false
opengraph: {}
title: hi! Im nathN
description: hi I'm nathN
